package https.webservices_sabre_com.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-08-05T06:00:29.641+05:30
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "SessionCloseRQService", 
                  wsdlLocation = "http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionCloseRQ.wsdl",
                  targetNamespace = "https://webservices.sabre.com/websvc") 
public class SessionCloseRQService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://webservices.sabre.com/websvc", "SessionCloseRQService");
    public final static QName SessionClosePortType = new QName("https://webservices.sabre.com/websvc", "SessionClosePortType");
    static {
        URL url = null;
        try {
            url = new URL("http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionCloseRQ.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SessionCloseRQService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionCloseRQ.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SessionCloseRQService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SessionCloseRQService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionCloseRQService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionCloseRQService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionCloseRQService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionCloseRQService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SessionClosePortType
     */
    @WebEndpoint(name = "SessionClosePortType")
    public SessionClosePortType getSessionClosePortType() {
        return super.getPort(SessionClosePortType, SessionClosePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionClosePortType
     */
    @WebEndpoint(name = "SessionClosePortType")
    public SessionClosePortType getSessionClosePortType(WebServiceFeature... features) {
        return super.getPort(SessionClosePortType, SessionClosePortType.class, features);
    }

}
